fileVersion: 1
id: "13"
mappingDefinitions:
  BRONZE:
    database: samples
    schema: tpch
  GOLD:
    database: doug_db_prod
    schema: gold
  SILVER:
    database: doug_db_prod
    schema: silver
  USER_ACCESS:
    database: doug_db_prod
    schema: access
name: Production
type: Environment
