fileVersion: 1
id: "13"
mappingDefinitions:
  DWH:
    database: doug_db_prod
    schema: dwh
  SRC:
    database: samples
    schema: tpch
  STAGE:
    database: doug_db_prod
    schema: stage
name: Production
type: Environment
